const {context,rows,fail}=require("./_lib");
const roles=["coach","manager","admin"];
async function access(c,id){if(c.roles.includes("coach")&&!c.roles.some(x=>["manager","admin"].includes(x))){const x=await rows(c.url,c.headers,`coach_students?coach_id=eq.${c.user.id}&student_id=eq.${id}&ended_at=is.null&select=id`);if(!x.length)throw Object.assign(new Error("Student not assigned"),{status:403});}}
const audit=(c,a,t,id,data)=>rows(c.url,c.headers,"rpc/write_audit_log",{method:"POST",body:JSON.stringify({p_actor:c.user.id,p_action:a,p_entity_type:t,p_entity_id:id,p_source:"mini_app",p_after:data})});
module.exports=async(req,res)=>{try{const c=await context(req,roles);
 if(req.method==="GET"){const studentId=String(req.query.student_id||"");const templates=await rows(c.url,c.headers,"training_templates?is_active=eq.true&select=*&order=name.asc");let plans=[],workouts=[];if(studentId){await access(c,studentId);plans=await rows(c.url,c.headers,`student_training_plans?student_id=eq.${studentId}&select=*&order=starts_on.desc`);workouts=await rows(c.url,c.headers,`planned_workouts?student_id=eq.${studentId}&select=*&order=planned_for.asc`);}return res.json({templates,plans,workouts});}
 if(req.method!=="POST")return res.status(405).json({error:"Method not allowed"});const b=req.body||{},action=String(b.action||"");
 if(action==="create_template"){const name=String(b.name||"").trim(),items=Array.isArray(b.items)?b.items:[];if(!name||!items.length)return res.status(400).json({error:"Template name and items required"});const t=(await rows(c.url,c.headers,"training_templates",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({name:name.slice(0,100),description:String(b.description||"").slice(0,500)||null,goal:String(b.goal||"").slice(0,100)||null,weeks:Number(b.weeks)||1,created_by:c.user.id})}))[0];let position=0;for(const item of items){position++;const exName=String(item.exerciseName||"").trim();if(!exName)continue;let ex=await rows(c.url,c.headers,`exercise_library?normalized_name=eq.${encodeURIComponent(exName.toLowerCase())}&select=id`);if(!ex[0])ex=await rows(c.url,c.headers,"exercise_library",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({name:exName,category:String(item.category||"").slice(0,80)||null,equipment:String(item.equipment||"").slice(0,80)||null,created_by:c.user.id})});await rows(c.url,c.headers,"training_template_items",{method:"POST",body:JSON.stringify({template_id:t.id,week_no:Number(item.weekNo)||1,day_no:Number(item.dayNo)||1,position,exercise_id:ex[0].id,exercise_name:exName,target_sets:Number(item.sets)||null,target_reps:String(item.reps||"").slice(0,30)||null,target_rpe:item.rpe==null?null:Number(item.rpe),rest_seconds:Number(item.restSeconds)||null,note:String(item.note||"").slice(0,300)||null})});}await audit(c,"create","training_template",t.id,t);return res.status(201).json({template:t});}
 if(action==="assign"){const studentId=String(b.studentId||""),templateId=String(b.templateId||""),startsOn=String(b.startsOn||"");if(!studentId||!templateId||!startsOn)return res.status(400).json({error:"Assignment fields required"});await access(c,studentId);const t=(await rows(c.url,c.headers,`training_templates?id=eq.${templateId}&select=*`))[0];if(!t)return res.status(404).json({error:"Template not found"});const items=await rows(c.url,c.headers,`training_template_items?template_id=eq.${templateId}&select=*&order=week_no.asc,day_no.asc,position.asc`);const plan=(await rows(c.url,c.headers,"student_training_plans",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({student_id:studentId,template_id:templateId,name:t.name,starts_on:startsOn,status:"active",assigned_by:c.user.id})}))[0];const grouped=new Map();for(const x of items){const key=`${x.week_no}-${x.day_no}`;if(!grouped.has(key))grouped.set(key,[]);grouped.get(key).push(x);}for(const [key,xs] of grouped){const [week,day]=key.split("-").map(Number),d=new Date(`${startsOn}T00:00:00Z`);d.setUTCDate(d.getUTCDate()+(week-1)*7+(day-1));await rows(c.url,c.headers,"planned_workouts",{method:"POST",body:JSON.stringify({plan_id:plan.id,student_id:studentId,planned_for:d.toISOString().slice(0,10),title:`${t.name}｜第${week}週第${day}天`,items:xs.map(x=>({exercise_name:x.exercise_name,sets:x.target_sets,reps:x.target_reps,rpe:x.target_rpe,rest_seconds:x.rest_seconds,note:x.note})),status:"planned"})});}await audit(c,"assign","student_training_plan",plan.id,plan);return res.status(201).json({plan});}
 return res.status(400).json({error:"Unsupported action"});}catch(e){return fail(res,e)}};
